Add issue template
fastruby/pecas pull request #65
Opened 2021-03-19 09:43 UTC by bronzdoc

Adds missing issue template

2021-03-23 17:18 UTC, rdormer approved these changes

2021-04-02 15:49 UTC, etagwerker requested changes
@bronzdoc I noticed a couple copy/paste issues 👍

2021-04-02 15:49 UTC, etagwerker commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Inform what version, branch, commit of Skunk you are using.
@bronzdoc Should say Pecas

2021-04-02 15:49 UTC, etagwerker commented on .github/ISSUE_TEMPLATE/feature_request.md
> +Inform what branch/commit/version of "Skunk" you are using.
@bronzdoc Should say Pecas

2021-04-06 02:44 UTC, bronzdoc commented
Addressed the issues @etagwerker, thanks

2021-04-06 02:44 UTC, merged